site_name: Engineering II Portfolio
site_description: Projects and notes from Engineering II
site_url: https://nathant-cell.github.io/eng2_portfolio/

theme:
  name: material
  palette:
    - scheme: dark
      primary: black
      accent: green

nav:
  - Home: index.md
  - Projects:
      - Portfolio: projects/portfolio_project.md
      - UV: projects/UV and Pip.md
      - Nicrome Wire Project: projects/Nicrome Wire.md
  - About: about.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
